### ISSUE TITLE
[rc.1] do operator breaks types. / Subjects need asObservable to keep types.

### ISSUE THREAD

**Issue by ovrmrw** [ReactiveX/rxjs#2029]
**RxJS version:** 5.0.0-rc.1

**Code to reproduce:** [https://github.com/ovrmrw/rxjs-marble-tests/blob/master/spec/forIssues/rc1-unexpected-behavior.ts](https://github.com/ovrmrw/rxjs-marble-tests/blob/master/spec/forIssues/rc1-unexpected-behavior.ts)

**Expected behavior:** `asObservable` is not needed for Subjects just to keep variable types. `do` operator should not break variable types.

**Actual behavior:** Subjects without `asObservable` all turn variable types into "any". `do` operator turns variable types into "{}".

**Additional information:** TypeScript 2.0.3 , VSCode 1.6.0

**Comment by david-driscoll** [comment]
This should be fixed with #2022

**Comment by ovrmrw** [comment]
`do` operator is ok by [#2222](https://github.com/ReactiveX/rxjs/pull/2022).
But an issue that Subject needs `asObservable` to keep types is still a problem.

**Comment by ovrmrw** [comment]
I confirmed to be solved the Subject issue. Great work! Should I close this issue?

**Comment by kwonoj** [comment]
Closing via #2035 .
