### ISSUE TITLE
All marble picture are broken

### ISSUE THREAD

**Issue by royling** [ReactiveX/rxjs#4366]
### Documentation Related To Component:
All

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

All pictures in the operators document are broken, eg. https://rxjs-dev.firebaseapp.com/defaultIfEmpty.png (404)

**Comment by martinsik** [comment]
This seems related to #4004, #4174 and #3796.

**Comment by JWO719** [comment]
Yeah I'm really sorry. We have this issue since quite a long time. We dis several attempts to try to fix it. Hopefully the last one solved it but we will see. I'll let you know when we deployed the docs the next time.

**Comment by wxt2005** [comment]
Well I've found those marble pictures broken for several months. I found it has been fixed in #3846 , Is there anything we can help to fix those pictures?

**Comment by sajidali** [comment]
It is 2019, and images are still broken. @JWO719 can you please prioritize this, as new learners don't have this important resource available from several months. 
Waiting for fix or update.

**Comment by JWO719** [comment]
I'm super sorry that this bug is still existing. Unfortunately the docs website isn't updated yet and there isn't much I can do about this. We will update the website with the next released version of rxjs.

**Comment by sajidali** [comment]
@JWO719 Thank you for the update, any alternatives we can try in the meantime?
looking forward to next released version of rxjs.

**Comment by scott-ho** [comment]
@JWO719 A release was issued 2 weeks ago, and the images are still broken.

**Comment by aastronaut** [comment]
Can confirm that the requests for the marble-diagram PNGs are still resulting in 404s (eg. https://rxjs-dev.firebaseapp.com/retry.png for the retry operator). Additionally the CSS rules will make Firefox use {width}x{width}px for the placeholder, resulting in 800x800px (depending on resolution) of empty image before any additional information continues (Chrome handles this better) - this is quite disappointing.

Only workaround so far seems to lookup the requested image in the repository (https://github.com/ReactiveX/rxjs/tree/master/docs_app/assets/images/marble-diagrams).

Seems like the requested routes are not handled correctly in the build step :/

**Comment by scott-ho** [comment]
@JWO719 That's strange.

There is no problem at my local machine with latest rxjs master. The docs app plays well on serve. And docs build is also ok with correct image url.

For example of `combineLatest`:
![image](https://user-images.githubusercontent.com/35443789/52996008-322b2c00-3457-11e9-9e14-721ddca6e8a9.png)

However, I can't figure out where is the code/script to strip those image address to be without prefix.

---

The `deploy-to-firebase.sh` looks good except for one ponit.

![image](https://user-images.githubusercontent.com/35443789/52996145-977f1d00-3457-11e9-8925-96555512b3e9.png)

the `--env` input for npm command has no effect at all, that's what the rule ought to be.

**Comment by aastronaut** [comment]
@scott-ho Maybe the images are also not uploaded?

following routes are all giving 404s:
- https://rxjs-dev.firebaseapp.com/retry.png
- https://rxjs-dev.firebaseapp.com/assets/retry.png
- https://rxjs-dev.firebaseapp.com/assets/images/retry.png
- https://rxjs-dev.firebaseapp.com/assets/images/marble-diagrams/retry.png

(the logo is found at https://rxjs-dev.firebaseapp.com/assets/images/logos/logo.png though)

dunno why there's `docs_app/src/assets/images/marble-diagrams/retry.png` and `docs_app/assets/images/marble-diagrams/retry.png` (note the _/src/_)?

I lack the info of how the build works, but the deployed path is the same as in the source code comment: `src/internal/operators/retry.ts#L12` -> `![](retry.png)` -> `https://rxjs-dev.firebaseapp.com/retry.png`
...would like to help fixing it, but I lack the knowledge of angular.

**Comment by dzhavat** [comment]
This image problem has remained unresolved for quite some time. I think it's annoying because people come to the docs to find info for how to use a certain thing and one of the most useful pieces is missing. Can't we really fix it? Having these diagrams in the docs will make them so much better.

One suggestion I have is to pin this issue to the top of the [issues] page so people can clearly see it and don't open more issues related to the same thing. Would that be possible? @JWO719 @cartant @benlesh

**Comment by xuemind** [comment]
I rebuilt a local version from master branch and deployed to my firebase. the image works correctly. Can we just rebuild and deploy if it can fix the issue? then you can find the root cause.
!{switchMap}(https://xm-firebase-sample.firebaseapp.com/api/operators/switchMap)

**Comment by JWO719** [comment]
Hopefully this is finally fixed with the next release of the docs. We worked on that issue quite often and for quite a long time. I'm really sorry for all the problems with it

**Comment by dzhavat** [comment]
Good news everyone 🎉 

There's been a new release. Finally, all marble images are working. 

This issue can be closed now (and hopefully not appear ever again) :)

**Comment by cartant** [comment]
I guess this can be closed.
