### ISSUE TITLE
Doc | Images don't load at operators section

### ISSUE THREAD

**Issue by abelardolg** [ReactiveX/rxjs#6683]
Hi there,

At this page: 
https://rxjs.dev/guide/operators

there is an error:
![image](https://user-images.githubusercontent.com/22522883/142890744-9357c124-9180-41bf-b6e1-471d281594e7.png)

Inspectioning:
![image](https://user-images.githubusercontent.com/22522883/142890601-7336461f-6e73-4967-8e1f-8cb9727a1882.png)

Best regards.

**Comment by jakovljevic-mladen** [comment]
Hi. This is fixed in #6558, but the latest version of the docs app is not yet published to rxjs.dev. Once it gets published, this problem will disappear.

**Comment by ThomasBower** [comment]
This is still broken. When will the latest version be published?

**Comment by BingeCode** [comment]
Still broken

**Comment by benlesh** [comment]
Hi @abelardolg — thank you for taking the time to open this issue and for sharing your thoughtful feedback with the RxJS project. I’m sorry it took us so long to respond. Given how much time has passed and the lack of recent activity, I’m going to close this for now so the tracker reflects the work we’re likely to act on. If this is still relevant on a current RxJS release, please feel welcome to open a new issue with updated context and a reproduction. Thank you again for your contribution and patience.

— Ben
