### ISSUE TITLE
Incorrect @deprecated for fromEvent overloads

### ISSUE THREAD

**Issue by jefbarn** [ReactiveX/rxjs#7401]
### Describe the bug

I think this @deprecated note is incorrect. Without the generic typescript can't infer the type.

```typescript
/** @deprecated Do not specify explicit type parameters. Signatures with type parameters that cannot be inferred will be removed in v8. */
export function fromEvent<T>(target: NodeStyleEventEmitter | ArrayLike<NodeStyleEventEmitter>, eventName: string): Observable<T>;
```

Same for:
```typescript
/** @deprecated Do not specify explicit type parameters. Signatures with type parameters that cannot be inferred will be removed in v8. */
export declare function fromEvent<T>(target: NodeCompatibleEventEmitter | ArrayLike<NodeCompatibleEventEmitter>, eventName: string): Observable<T>;
```

Also should probably ADD @deprecated warnings for the overloads with resultSelector.

### Expected behavior

It should be like
```typescript
export declare function fromEvent<T>(target: HasEventTargetAddRemove<T> | ArrayLike<HasEventTargetAddRemove<T>>, eventName: string): Observable<T>;
```
which is similar generic signature but not deprecated ¯\_(ツ)_/¯ 

### Version

7.8.1

**Comment by benlesh** [comment]
Hmm... that is weird. Thank you for pointing that out.

**Comment by benlesh** [comment]
Resolved with #7406

**Comment by vabatta** [comment]
On `7.8.1` I still get the `deprecated` when using it on nodejs event emitter, is this correct? @benlesh
